global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    scheme: https
    tls_config:
      insecure_skip_verify: true  # 자체 서명된 인증서를 사용하는 경우
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['aiddoru-backend-aiddoru-1:8080']  # HTTPS 포트 사용
#      - targets: ['aiddoru-aiddoru-1:8080']
